- name: Configure Home
  hosts: home_servers
  become: true
  tasks:
    - name: Creating index file 
      copy: 
        dest: "/var/www/html/index.html"
        content: |
          Home App service hello home
          This app takes care or app services new changes pushed
