- name: Configure Products
  hosts: products_servers
  become: true
  tasks:
    - name: Creating a new directory
      file:
        path: "/var/www/html/products/"
        state: directory
    - name: Creating index file
      copy:
        dest: "/var/www/html/products/index.html"
        content: |
          <html><center><h1>Products App service
          Takes Care of products app and services</h1></center></html>
