- name: Configure Home
  hosts: home_servers
  become: true
  tasks:
    - name: Creating index file 
      copy: 
        dest: "/var/www/html/index.html"
        content: |
          <html><center><h1>Products App service
          Takes Care of products app</h1></center></html>
