- name: Playbook
  hosts: home_servers,product_servers
  become: yes
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: ensure apache is at the latest version
      yum:
        name: httpd
        state: latest
    - name: ensure apache is running
      service:
        name: httpd
        state: started