name: Checking ansible configuration

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  validate:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"

  setup-ansible:
    needs: [validate]
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: write inventory to file
        env:
          INVENTORY: ${{ secrets.INVENTORY }}
          TEST: ${{ secrets.TF_API_TOKEN }}
        run: |
          echo $TEST >> test.txt
          echo test.txt
          echo $INVENTORY
          echo "$INVENTORY" > inventory
          cat inventory

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: run playbook
        run: |
          ansible-playbook -i inventory ansible/webserver.yml
    