
name: Planning and lint checking for PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Plan_Configuration:
    name: "Plan Terraform Configuration"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      
      - name: checkout Repository code
        uses: actions/checkout@v3
        with:
          ref: feature
     
      - name: Print MetaData
        run: |
          echo "This event was triggered by the user ${{ github.actor }}"
          echo "The triggered event was ${{ github.event_name }}"
          echo "The ref is ${{ github.ref }} "

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Properly format the code
        id: fmt
        run: terraform fmt -recursive
        
      - name: Init the terraform
        id: init
        run: terraform init
        
      - name: Plan the Terraform configuration
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  Webserver_Configure_Test:
    runs-on: ubuntu-latest
    needs: [Plan_Configuration]
    environment: AWS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: feature
      - name: write inventory to file
        run: |
          echo ${{ secrets.INVENTORY }} | base64 -d > inventory
          echo ${{ secrets.PRIVATE_KEY }} > privateKey
          cat inventory
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Apache on webservers
        run: |
          ansible webservers --list-hosts -i inventory
          ansible-playbook -i inventory --private-key privateKey ansible/webserver.yml
  validate_ansible:
    runs-on: ubuntu-latest
    needs: [Plan_Configuration]
    name: "Ansible lint checking"
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: feature
      
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"
