
name: Planning and lint checking for PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Plan_Configuration:
    name: "Plan Terraform Configuration"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:

      - name: checkout Repository code
        uses: actions/checkout@v3
        with:
          ref: feature
     
      - name: Print MetaData
        run: |
          echo "This event was triggered by the user ${{ github.actor }}"
          echo "The triggered event was ${{ github.event_name }}"
          echo "The ref is ${{ github.ref }} "

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Cache Terraform
        id: cache_terraform
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/.terraformrc
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Properly format the code
        id: fmt
        run: terraform fmt -recursive
        
      - name: Init the terraform
        id: init
        if: steps.cache_terraform.outputs.cache-hit != 'true'
        run: terraform init
        
      - name: Plan the Terraform configuration
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  validate_ansible:
    runs-on: ubuntu-latest
    needs: [Plan_Configuration]
    name: "Ansible lint checking"
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: feature
      
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"
